#ifndef _OAL_EVENT_H_
#define _OAL_EVENT_H_

#define OAL_EVENT_BASE_						(200)

#define OAL_EVENT_WLAN_INIT_DONE				(OAL_EVENT_BASE_+101)
#define OAL_EVENT_NORMAL_CONNECTING				(OAL_EVENT_BASE_+102)
#define OAL_EVENT_NORMAL_CONNECTED				(OAL_EVENT_BASE_+103)
#define OAL_EVENT_NORMAL_CONNECT_FAILED			(OAL_EVENT_BASE_+104)
#define OAL_EVENT_NORMAL_LINK_LOST				(OAL_EVENT_BASE_+105)
#define OAL_EVENT_NORMAL_USER_DISCONNECT		(OAL_EVENT_BASE_+106)
#define OAL_EVENT_PROV_WPS_SSID_SELECT_REQ		(OAL_EVENT_BASE_+107)
#define OAL_EVENT_PROV_WPS_SUCCESSFUL			(OAL_EVENT_BASE_+108)
#define OAL_EVENT_PROV_WPS_UNSUCCESSFUL			(OAL_EVENT_BASE_+109)
#define OAL_EVENT_NORMAL_RESET_PROV				(OAL_EVENT_BASE_+110)
#define OAL_EVENT_UAP_STARTED					(OAL_EVENT_BASE_+111)
#define OAL_EVENT_PROV_CLIENT_DONE				(OAL_EVENT_BASE_+112)
#define OAL_EVENT_AIRKISS_TIMEOUT				(OAL_EVENT_BASE_+201)
#define OAL_EVENT_OAL_AUTH_FAILED				(OAL_EVENT_BASE_+204)
#define OAL_EVENT_OAL_NETWORK_NOT_FOUND			(OAL_EVENT_BASE_+205)
#define OAL_EVENT_OAL_DHCP_FAILED				(OAL_EVENT_BASE_+206)
#define OAL_EVENT_CONNECT_APS					(OAL_EVENT_BASE_+208)

typedef int(*OAL_EVENT_CALLBACK)(int evt, void *data);

#endif
